name: GH Pages Prep
on:
  push:
    branches:
      - main

jobs:
  config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set theme
        run: python ./.github/workflows/gh-prep.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: gh-pages
          create_branch: true
          push_options: '--force'
